nova-<*>-05-<*> 2017-05-<*> <*> <*> INFO nova.osapi_compute.wsgi.server [req-<*>-<*>-<*>-<*>-<*> <*> <*> - - -] <*> <*> <*> HTTP/1.1" status: <*> len: <*> time: <*>
nova-<*>-05-<*> 2017-05-<*> <*> 2931 INFO nova.compute.manager [req-3ea4052c-895d-4b64-9e2d-04d64c4d94ab - - - - -] [instance: <*>-<*>-<*>-<*>-<*>] VM <*> (Lifecycle Event)
nova-<*>-05-<*> 2017-05-<*> <*> 2931 INFO nova.compute.manager [req-3ea4052c-895d-4b64-9e2d-04d64c4d94ab - - - - -] [instance: <*>-<*>-<*>-<*>-<*>] During sync_power_state the instance has a pending task (spawning). Skip.
nova-<*>-05-<*> 2017-05-<*> <*> 2931 INFO <*> [req-addc1839-2ed5-4778-b57e-5854eb7b8b09 - - - - -] <*> <*><*><*><*><*><*><*>-<*><*><*><*><*><*><*>
nova-<*>-05-<*> 2017-05-<*> <*> 2931 INFO nova.virt.libvirt.imagecache [req-addc1839-2ed5-4778-b57e-5854eb7b8b09 - - - - -] image 0673dd71-34c5-4fbb-86c4-40623fbe45b4 at (/var/lib/nova/instances/_base/a489c868f0c37da93b76227c91bb03908ac0e742): in use: on this node 1 local, 0 on other nodes sharing this instance storage
nova-<*>-05-<*> 2017-05-<*> <*> 2931 <*> nova.virt.libvirt.imagecache [req-addc1839-2ed5-4778-b57e-5854eb7b8b09 - - - - -] <*> base <*> /var/lib/nova/instances/_base/a489c868f0c37da93b76227c91bb03908ac0e742
nova-<*>-05-<*> 2017-05-<*> <*> <*> INFO nova.api.openstack.compute.server_external_events [req-<*>-<*>-<*>-<*>-<*> f7b8d1f1d4d44643b07fa10ca7d021fb e9746973ac574c6b8a9e8857f56a7608 - - -] Creating event network-vif-<*>-<*>-<*>-<*>-<*> for instance <*>-<*>-<*>-<*>-<*>
nova-<*>-05-<*> 2017-05-<*> <*> <*> INFO nova.osapi_compute.wsgi.server [req-<*>-<*>-<*>-<*>-<*> <*> e9746973ac574c6b8a9e8857f56a7608 - - -] 10.11.10.1 <*> <*>-<*>-<*>-<*> HTTP/1.1" status: <*> len: <*> time: <*>
nova-<*>-05-<*> 2017-05-<*> <*> 2931 INFO nova.virt.libvirt.driver [-] [instance: <*>-<*>-<*>-<*>-<*>] Instance <*> successfully.
nova-<*>-05-<*> 2017-05-<*> <*> 2931 INFO nova.compute.manager [req-<*>-<*>-<*>-<*>-<*> 113d3a99c3da401fbd62cc2caa5b96d2 54fadb412c4e40cdbaed9335e4c35a9e - - -] [instance: <*>-<*>-<*>-<*>-<*>] Took <*> seconds to <*> the instance on the hypervisor.
nova-<*>-05-<*> 2017-05-<*> <*> 2931 INFO nova.compute.manager [req-<*>-<*>-<*>-<*>-<*> 113d3a99c3da401fbd62cc2caa5b96d2 54fadb412c4e40cdbaed9335e4c35a9e - - -] [instance: <*>-<*>-<*>-<*>-<*>] Took <*> seconds to build instance.
nova-<*>-05-<*> 2017-05-<*> <*> 2931 INFO nova.compute.resource_tracker [req-addc1839-2ed5-4778-b57e-5854eb7b8b09 - - - - -] Auditing locally available compute resources for node cp-1.slowvm1.tcloud-pg0.utah.cloudlab.us
nova-<*>-05-<*> 2017-05-<*> <*> 2931 INFO nova.compute.resource_tracker [req-addc1839-2ed5-4778-b57e-5854eb7b8b09 - - - - -] Total usable vcpus: 16, total allocated vcpus: <*>
nova-<*>-05-<*> 2017-05-<*> <*> 2931 INFO nova.compute.resource_tracker [req-addc1839-2ed5-4778-b57e-5854eb7b8b09 - - - - -] Final resource view: name=cp-1.slowvm1.tcloud-pg0.utah.cloudlab.us phys_ram=64172MB <*> phys_disk=15GB <*> total_vcpus=16 <*> pci_stats=[]
nova-<*>-05-<*> 2017-05-<*> <*> <*> INFO nova.metadata.wsgi.server [req-<*>-<*>-<*>-<*>-<*> - - - - -] <*>,10.11.10.1 "GET <*>-<*>-<*> HTTP/1.1" status: <*> len: <*> time: <*>
nova-<*>-05-<*> 2017-05-<*> <*> <*> INFO nova.metadata.wsgi.server [-] <*>,10.11.10.1 "GET <*>-<*>-<*> HTTP/1.1" status: <*> len: <*> time: <*>
nova-<*>-05-<*> 2017-05-<*> <*> <*> INFO nova.osapi_compute.wsgi.server [req-<*>-<*>-<*>-<*>-<*> <*> <*> - - -] <*> <*> <*>-<*>-<*>-<*>-<*> HTTP/1.1" status: <*> len: <*> time: <*>
nova-<*>-05-<*> 2017-05-<*> <*> 2931 INFO <*> [req-<*>-<*>-<*>-<*>-<*> 113d3a99c3da401fbd62cc2caa5b96d2 54fadb412c4e40cdbaed9335e4c35a9e - - -] [instance: <*>-<*>-<*>-<*>-<*>] <*> <*>
nova-<*>-05-<*> 2017-05-<*> <*> 2931 INFO nova.virt.libvirt.driver [req-<*>-<*>-<*>-<*>-<*> 113d3a99c3da401fbd62cc2caa5b96d2 54fadb412c4e40cdbaed9335e4c35a9e - - -] [instance: <*>-<*>-<*>-<*>-<*>] <*> <*> <*><*><*>-<*>-<*>-<*><*><*>
nova-<*>-05-<*> 2017-05-<*> <*> 2931 INFO nova.compute.manager [req-<*>-<*>-<*>-<*>-<*> <*> 54fadb412c4e40cdbaed9335e4c35a9e - - -] [instance: <*>-<*>-<*>-<*>-<*>] Took <*> seconds to deallocate network for instance.
nova-<*>-05-<*> 2017-05-<*> <*> 2931 INFO nova.virt.libvirt.imagecache [req-addc1839-2ed5-4778-b57e-5854eb7b8b09 - - - - -] Removing base or swap file: /var/lib/nova/instances/_base/a489c868f0c37da93b76227c91bb03908ac0e742
nova-<*>-05-<*> 2017-05-<*> <*> 25746 INFO nova.api.openstack.wsgi [req-<*>-<*>-<*>-<*>-<*> f7b8d1f1d4d44643b07fa10ca7d021fb e9746973ac574c6b8a9e8857f56a7608 - - -] HTTP exception thrown: No instances found for any event
nova-<*>-05-<*> 2017-05-<*> <*> 2931 INFO nova.compute.claims [req-<*>-<*>-<*>-<*>-<*> 113d3a99c3da401fbd62cc2caa5b96d2 54fadb412c4e40cdbaed9335e4c35a9e - - -] [instance: <*>-<*>-<*>-<*>-<*>] Attempting claim: memory 2048 MB, disk 20 GB, vcpus 1 CPU
nova-<*>-05-<*> 2017-05-<*> <*> 2931 INFO nova.compute.claims [req-<*>-<*>-<*>-<*>-<*> 113d3a99c3da401fbd62cc2caa5b96d2 54fadb412c4e40cdbaed9335e4c35a9e - - -] [instance: <*>-<*>-<*>-<*>-<*>] <*> <*> <*> <*>, <*> <*> <*>
nova-<*>-05-<*> 2017-05-<*> <*> 2931 INFO nova.compute.manager [-] [instance: <*>-<*>-<*>-<*>-<*>] VM Stopped (Lifecycle Event)
nova-<*>-05-<*> 2017-05-<*> <*> 25998 INFO nova.scheduler.host_manager [req-<*>-<*>-<*>-<*>-<*> - - - - -] Successfully synced instances from host 'cp-1.slowvm1.tcloud-pg0.utah.cloudlab.us'.
nova-<*>-05-<*> 2017-05-<*> <*> <*> INFO nova.metadata.wsgi.server [-] <*>,10.11.10.1 "GET /latest/meta-<*> HTTP/1.1" status: 200 len: <*> time: <*>
nova-<*>-05-<*> 2017-05-<*> <*> <*> INFO nova.metadata.wsgi.server [-] <*>,10.11.10.1 "GET /latest/meta-<*>-<*>-<*> HTTP/1.1" status: 200 len: <*> time: <*>
nova-<*>-05-<*> 2017-05-<*> <*> <*> INFO nova.metadata.wsgi.server [req-<*>-<*>-<*>-<*>-<*> - - - - -] <*>,10.11.10.1 "GET /latest/meta-<*> HTTP/1.1" status: 200 len: <*> time: <*>
nova-<*>-05-<*> 2017-05-<*> <*> 2931 INFO nova.compute.manager [req-addc1839-2ed5-4778-b57e-5854eb7b8b09 - - - - -] Running instance usage audit for host cp-1.slowvm1.tcloud-pg0.utah.cloudlab.us from 2017-05-<*> <*> to 2017-05-<*> <*> <*> instances.
nova-<*>-05-<*> 2017-05-<*> <*> 2931 INFO nova.virt.libvirt.imagecache [req-addc1839-2ed5-4778-b57e-5854eb7b8b09 - - - - -] Base or swap file too young to remove: /var/lib/nova/instances/_base/a489c868f0c37da93b76227c91bb03908ac0e742
nova-<*>-05-<*> 2017-05-<*> <*> <*> INFO nova.metadata.wsgi.server [req-<*>-<*>-<*>-<*>-<*> - - - - -] <*>,10.11.10.1 "GET /latest/meta-<*>-<*>-<*> HTTP/1.1" status: 200 len: <*> time: <*>
nova-<*>-05-<*> 2017-05-<*> <*> 25998 INFO nova.scheduler.host_manager [req-<*>-<*>-<*>-<*>-<*> - - - - -] The instance sync for host 'cp-1.slowvm1.tcloud-pg0.utah.cloudlab.us' did not match. Re-created its InstanceList.
nova-<*>-05-<*> 2017-05-<*> <*> 25740 INFO nova.osapi_compute.wsgi.server [req-<*>-<*>-<*>-<*>-<*> d16a600c5e2a47fe98aee00ee4cb9743 e9746973ac574c6b8a9e8857f56a7608 - - -] 10.11.10.2 "GET /v2/e9746973ac574c6b8a9e8857f56a7608/servers/detail?all_tenants=True&changes-since=2017-05-<*>-1.slowvm1.tcloud-pg0.utah.cloudlab.us HTTP/1.1" status: 200 len: <*> time: <*>
nova-<*>-05-<*> 2017-05-<*> <*> 2931 WARNING nova.compute.manager [req-addc1839-2ed5-4778-b57e-5854eb7b8b09 - - - - -] While synchronizing instance power states, found 1 instances in the database and 0 instances on the hypervisor.
nova-<*>-05-<*> 2017-05-<*> <*> 2931 INFO nova.compute.manager [-] [instance: <*>-<*>-<*>-<*>-<*>] During sync_power_state the instance has a pending task <*> Skip.
nova-<*>-05-<*> 2017-05-<*> <*> 2931 WARNING nova.virt.libvirt.driver [req-addc1839-2ed5-4778-b57e-5854eb7b8b09 - - - - -] couldn't obtain the vcpu count from domain id: <*>-<*>-<*>-<*>-<*>, exception: Requested operation is not valid: cpu affinity is not supported
nova-compute.log.1.2017-05-<*> 2017-05-<*> <*> 2931 ERROR oslo_service.periodic_task [req-addc1839-2ed5-4778-b57e-5854eb7b8b09 - - - - -] Error during ComputeManager._run_image_cache_manager_pass
nova-compute.log.1.2017-05-<*> 2017-05-<*> <*> 2931 ERROR oslo_service.periodic_task <*> <*> <*> <*> <*>
nova-compute.log.1.2017-05-<*> 2017-05-<*> <*> 2931 ERROR oslo_service.periodic_task   File "/usr/lib/python2.7/dist-<*>, line <*>, in <*>
nova-compute.log.1.2017-05-<*> 2017-05-<*> <*> 2931 ERROR oslo_service.periodic_task     <*>, <*>
nova-compute.log.1.2017-05-<*> 2017-05-<*> <*> 2931 ERROR oslo_service.periodic_task     self._age_and_verify_cached_images(context, all_instances, base_dir)
nova-compute.log.1.2017-05-<*> 2017-05-<*> <*> 2931 ERROR oslo_service.periodic_task     inuse_backing_images = self._list_backing_images()
nova-compute.log.1.2017-05-<*> 2017-05-<*> <*> 2931 ERROR oslo_service.periodic_task     backing_file = images.qemu_img_info(path, format).backing_file
nova-compute.log.1.2017-05-<*> 2017-05-<*> <*> 2931 ERROR oslo_service.periodic_task     raise exception.InvalidDiskInfo(reason=msg)
nova-compute.log.1.2017-05-<*> 2017-05-<*> <*> 2931 ERROR oslo_service.periodic_task InvalidDiskInfo: Disk info file is invalid: qemu-img failed to execute on <*>-<*>-<*>-<*>-<*> : Unexpected error while running command.
nova-compute.log.1.2017-05-<*> 2017-05-<*> <*> 2931 ERROR oslo_service.periodic_task Command: /usr/bin/python -m oslo_concurrency.prlimit --as=1073741824 --cpu=2 -- env LC_ALL=C LANG=C qemu-img info <*>-<*>-<*>-<*>-<*>
nova-compute.log.1.2017-05-<*> 2017-05-<*> <*> 2931 ERROR oslo_service.periodic_task Exit code: 1
nova-compute.log.1.2017-05-<*> 2017-05-<*> <*> 2931 ERROR oslo_service.periodic_task Stdout: u''
nova-compute.log.1.2017-05-<*> 2017-05-<*> <*> 2931 ERROR oslo_service.periodic_task Stderr: u"qemu-img: Could not open <*>-<*>-<*>-<*>-<*> Could not open <*>-<*>-<*>-<*>-<*> No such file or directory\n"
nova-compute.log.1.2017-05-<*> 2017-05-<*> <*> 2931 ERROR oslo_service.periodic_task
nova-api.log.1.2017-05-<*> 2017-05-<*> <*> <*> ERROR keystonemiddleware.auth_token [req-<*>-<*>-<*>-<*>-<*> 113d3a99c3da401fbd62cc2caa5b96d2 54fadb412c4e40cdbaed9335e4c35a9e - - -] Bad response code while validating token: 503
nova-api.log.1.2017-05-<*> 2017-05-<*> <*> <*> WARNING keystonemiddleware.auth_token [req-<*>-<*>-<*>-<*>-<*> 113d3a99c3da401fbd62cc2caa5b96d2 54fadb412c4e40cdbaed9335e4c35a9e - - -] Identity response: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
nova-api.log.1.2017-05-<*> 2017-05-<*> <*> <*> CRITICAL keystonemiddleware.auth_token [req-<*>-<*>-<*>-<*>-<*> 113d3a99c3da401fbd62cc2caa5b96d2 54fadb412c4e40cdbaed9335e4c35a9e - - -] Unable to validate token: Failed to fetch token data from identity server
